# Autogenerated wrapper script for GAP_pkg_caratinterface_jll for aarch64-apple-darwin
export Add, Aut_grp, Bravais_catalog, Bravais_equiv, Bravais_grp, Bravais_inclusions, Bravais_type, Conj, Conj_bravais, Conjugated, Conv, Datei, Elt, Extensions, Extract, First_perfect, Form_elt, Form_space, Formtovec, Full, Gauss, Graph, Idem, Inv, Invar_space, Is_finite, Isometry, KSubgroups, KSupergroups, Kron, Long_solve, Ltm, Mink_red, Minpol, Modp, Mtl, Mul, Name, Normalizer, Normalizer_in_N, Normlin, Orbit, Order_, P_lse_solve, Pair_red, Pdet, Perfect_neighbours, Polyeder, Presentation, Q_catalog, QtoZ, Red_gen, Rein, Rest_short, Reverse_name, Rform, Same_generators, Scalarmul, Scpr, Short, Short_reduce, Shortest, Signature, Simplify_mat, Standard_affine_form, Sublattices, Symbol_, TSubgroups, TSupergroups, Torsionfree, Tr, Tr_bravais, Trace, Trbifo, Vectoform, Vector_systems, Vor_vertices, ZZprog, Z_equiv, Zass_main

using GMP_jll
JLLWrappers.@generate_wrapper_header("GAP_pkg_caratinterface")
JLLWrappers.@declare_executable_product(Add)
JLLWrappers.@declare_executable_product(Aut_grp)
JLLWrappers.@declare_executable_product(Bravais_catalog)
JLLWrappers.@declare_executable_product(Bravais_equiv)
JLLWrappers.@declare_executable_product(Bravais_grp)
JLLWrappers.@declare_executable_product(Bravais_inclusions)
JLLWrappers.@declare_executable_product(Bravais_type)
JLLWrappers.@declare_executable_product(Conj)
JLLWrappers.@declare_executable_product(Conj_bravais)
JLLWrappers.@declare_executable_product(Conjugated)
JLLWrappers.@declare_executable_product(Conv)
JLLWrappers.@declare_executable_product(Datei)
JLLWrappers.@declare_executable_product(Elt)
JLLWrappers.@declare_executable_product(Extensions)
JLLWrappers.@declare_executable_product(Extract)
JLLWrappers.@declare_executable_product(First_perfect)
JLLWrappers.@declare_executable_product(Form_elt)
JLLWrappers.@declare_executable_product(Form_space)
JLLWrappers.@declare_executable_product(Formtovec)
JLLWrappers.@declare_executable_product(Full)
JLLWrappers.@declare_executable_product(Gauss)
JLLWrappers.@declare_executable_product(Graph)
JLLWrappers.@declare_executable_product(Idem)
JLLWrappers.@declare_executable_product(Inv)
JLLWrappers.@declare_executable_product(Invar_space)
JLLWrappers.@declare_executable_product(Is_finite)
JLLWrappers.@declare_executable_product(Isometry)
JLLWrappers.@declare_executable_product(KSubgroups)
JLLWrappers.@declare_executable_product(KSupergroups)
JLLWrappers.@declare_executable_product(Kron)
JLLWrappers.@declare_executable_product(Long_solve)
JLLWrappers.@declare_executable_product(Ltm)
JLLWrappers.@declare_executable_product(Mink_red)
JLLWrappers.@declare_executable_product(Minpol)
JLLWrappers.@declare_executable_product(Modp)
JLLWrappers.@declare_executable_product(Mtl)
JLLWrappers.@declare_executable_product(Mul)
JLLWrappers.@declare_executable_product(Name)
JLLWrappers.@declare_executable_product(Normalizer)
JLLWrappers.@declare_executable_product(Normalizer_in_N)
JLLWrappers.@declare_executable_product(Normlin)
JLLWrappers.@declare_executable_product(Orbit)
JLLWrappers.@declare_executable_product(Order_)
JLLWrappers.@declare_executable_product(P_lse_solve)
JLLWrappers.@declare_executable_product(Pair_red)
JLLWrappers.@declare_executable_product(Pdet)
JLLWrappers.@declare_executable_product(Perfect_neighbours)
JLLWrappers.@declare_executable_product(Polyeder)
JLLWrappers.@declare_executable_product(Presentation)
JLLWrappers.@declare_executable_product(Q_catalog)
JLLWrappers.@declare_executable_product(QtoZ)
JLLWrappers.@declare_executable_product(Red_gen)
JLLWrappers.@declare_executable_product(Rein)
JLLWrappers.@declare_executable_product(Rest_short)
JLLWrappers.@declare_executable_product(Reverse_name)
JLLWrappers.@declare_executable_product(Rform)
JLLWrappers.@declare_executable_product(Same_generators)
JLLWrappers.@declare_executable_product(Scalarmul)
JLLWrappers.@declare_executable_product(Scpr)
JLLWrappers.@declare_executable_product(Short)
JLLWrappers.@declare_executable_product(Short_reduce)
JLLWrappers.@declare_executable_product(Shortest)
JLLWrappers.@declare_executable_product(Signature)
JLLWrappers.@declare_executable_product(Simplify_mat)
JLLWrappers.@declare_executable_product(Standard_affine_form)
JLLWrappers.@declare_executable_product(Sublattices)
JLLWrappers.@declare_executable_product(Symbol_)
JLLWrappers.@declare_executable_product(TSubgroups)
JLLWrappers.@declare_executable_product(TSupergroups)
JLLWrappers.@declare_executable_product(Torsionfree)
JLLWrappers.@declare_executable_product(Tr)
JLLWrappers.@declare_executable_product(Tr_bravais)
JLLWrappers.@declare_executable_product(Trace)
JLLWrappers.@declare_executable_product(Trbifo)
JLLWrappers.@declare_executable_product(Vectoform)
JLLWrappers.@declare_executable_product(Vector_systems)
JLLWrappers.@declare_executable_product(Vor_vertices)
JLLWrappers.@declare_executable_product(ZZprog)
JLLWrappers.@declare_executable_product(Z_equiv)
JLLWrappers.@declare_executable_product(Zass_main)
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll)
    JLLWrappers.@init_executable_product(
        Add,
        "bin/Add",
    )

    JLLWrappers.@init_executable_product(
        Aut_grp,
        "bin/Aut_grp",
    )

    JLLWrappers.@init_executable_product(
        Bravais_catalog,
        "bin/Bravais_catalog",
    )

    JLLWrappers.@init_executable_product(
        Bravais_equiv,
        "bin/Bravais_equiv",
    )

    JLLWrappers.@init_executable_product(
        Bravais_grp,
        "bin/Bravais_grp",
    )

    JLLWrappers.@init_executable_product(
        Bravais_inclusions,
        "bin/Bravais_inclusions",
    )

    JLLWrappers.@init_executable_product(
        Bravais_type,
        "bin/Bravais_type",
    )

    JLLWrappers.@init_executable_product(
        Conj,
        "bin/Conj",
    )

    JLLWrappers.@init_executable_product(
        Conj_bravais,
        "bin/Conj_bravais",
    )

    JLLWrappers.@init_executable_product(
        Conjugated,
        "bin/Conjugated",
    )

    JLLWrappers.@init_executable_product(
        Conv,
        "bin/Conv",
    )

    JLLWrappers.@init_executable_product(
        Datei,
        "bin/Datei",
    )

    JLLWrappers.@init_executable_product(
        Elt,
        "bin/Elt",
    )

    JLLWrappers.@init_executable_product(
        Extensions,
        "bin/Extensions",
    )

    JLLWrappers.@init_executable_product(
        Extract,
        "bin/Extract",
    )

    JLLWrappers.@init_executable_product(
        First_perfect,
        "bin/First_perfect",
    )

    JLLWrappers.@init_executable_product(
        Form_elt,
        "bin/Form_elt",
    )

    JLLWrappers.@init_executable_product(
        Form_space,
        "bin/Form_space",
    )

    JLLWrappers.@init_executable_product(
        Formtovec,
        "bin/Formtovec",
    )

    JLLWrappers.@init_executable_product(
        Full,
        "bin/Full",
    )

    JLLWrappers.@init_executable_product(
        Gauss,
        "bin/Gauss",
    )

    JLLWrappers.@init_executable_product(
        Graph,
        "bin/Graph",
    )

    JLLWrappers.@init_executable_product(
        Idem,
        "bin/Idem",
    )

    JLLWrappers.@init_executable_product(
        Inv,
        "bin/Inv",
    )

    JLLWrappers.@init_executable_product(
        Invar_space,
        "bin/Invar_space",
    )

    JLLWrappers.@init_executable_product(
        Is_finite,
        "bin/Is_finite",
    )

    JLLWrappers.@init_executable_product(
        Isometry,
        "bin/Isometry",
    )

    JLLWrappers.@init_executable_product(
        KSubgroups,
        "bin/KSubgroups",
    )

    JLLWrappers.@init_executable_product(
        KSupergroups,
        "bin/KSupergroups",
    )

    JLLWrappers.@init_executable_product(
        Kron,
        "bin/Kron",
    )

    JLLWrappers.@init_executable_product(
        Long_solve,
        "bin/Long_solve",
    )

    JLLWrappers.@init_executable_product(
        Ltm,
        "bin/Ltm",
    )

    JLLWrappers.@init_executable_product(
        Mink_red,
        "bin/Mink_red",
    )

    JLLWrappers.@init_executable_product(
        Minpol,
        "bin/Minpol",
    )

    JLLWrappers.@init_executable_product(
        Modp,
        "bin/Modp",
    )

    JLLWrappers.@init_executable_product(
        Mtl,
        "bin/Mtl",
    )

    JLLWrappers.@init_executable_product(
        Mul,
        "bin/Mul",
    )

    JLLWrappers.@init_executable_product(
        Name,
        "bin/Name",
    )

    JLLWrappers.@init_executable_product(
        Normalizer,
        "bin/Normalizer",
    )

    JLLWrappers.@init_executable_product(
        Normalizer_in_N,
        "bin/Normalizer_in_N",
    )

    JLLWrappers.@init_executable_product(
        Normlin,
        "bin/Normlin",
    )

    JLLWrappers.@init_executable_product(
        Orbit,
        "bin/Orbit",
    )

    JLLWrappers.@init_executable_product(
        Order_,
        "bin/Order",
    )

    JLLWrappers.@init_executable_product(
        P_lse_solve,
        "bin/P_lse_solve",
    )

    JLLWrappers.@init_executable_product(
        Pair_red,
        "bin/Pair_red",
    )

    JLLWrappers.@init_executable_product(
        Pdet,
        "bin/Pdet",
    )

    JLLWrappers.@init_executable_product(
        Perfect_neighbours,
        "bin/Perfect_neighbours",
    )

    JLLWrappers.@init_executable_product(
        Polyeder,
        "bin/Polyeder",
    )

    JLLWrappers.@init_executable_product(
        Presentation,
        "bin/Presentation",
    )

    JLLWrappers.@init_executable_product(
        Q_catalog,
        "bin/Q_catalog",
    )

    JLLWrappers.@init_executable_product(
        QtoZ,
        "bin/QtoZ",
    )

    JLLWrappers.@init_executable_product(
        Red_gen,
        "bin/Red_gen",
    )

    JLLWrappers.@init_executable_product(
        Rein,
        "bin/Rein",
    )

    JLLWrappers.@init_executable_product(
        Rest_short,
        "bin/Rest_short",
    )

    JLLWrappers.@init_executable_product(
        Reverse_name,
        "bin/Reverse_name",
    )

    JLLWrappers.@init_executable_product(
        Rform,
        "bin/Rform",
    )

    JLLWrappers.@init_executable_product(
        Same_generators,
        "bin/Same_generators",
    )

    JLLWrappers.@init_executable_product(
        Scalarmul,
        "bin/Scalarmul",
    )

    JLLWrappers.@init_executable_product(
        Scpr,
        "bin/Scpr",
    )

    JLLWrappers.@init_executable_product(
        Short,
        "bin/Short",
    )

    JLLWrappers.@init_executable_product(
        Short_reduce,
        "bin/Short_reduce",
    )

    JLLWrappers.@init_executable_product(
        Shortest,
        "bin/Shortest",
    )

    JLLWrappers.@init_executable_product(
        Signature,
        "bin/Signature",
    )

    JLLWrappers.@init_executable_product(
        Simplify_mat,
        "bin/Simplify_mat",
    )

    JLLWrappers.@init_executable_product(
        Standard_affine_form,
        "bin/Standard_affine_form",
    )

    JLLWrappers.@init_executable_product(
        Sublattices,
        "bin/Sublattices",
    )

    JLLWrappers.@init_executable_product(
        Symbol_,
        "bin/Symbol",
    )

    JLLWrappers.@init_executable_product(
        TSubgroups,
        "bin/TSubgroups",
    )

    JLLWrappers.@init_executable_product(
        TSupergroups,
        "bin/TSupergroups",
    )

    JLLWrappers.@init_executable_product(
        Torsionfree,
        "bin/Torsionfree",
    )

    JLLWrappers.@init_executable_product(
        Tr,
        "bin/Tr",
    )

    JLLWrappers.@init_executable_product(
        Tr_bravais,
        "bin/Tr_bravais",
    )

    JLLWrappers.@init_executable_product(
        Trace,
        "bin/Trace",
    )

    JLLWrappers.@init_executable_product(
        Trbifo,
        "bin/Trbifo",
    )

    JLLWrappers.@init_executable_product(
        Vectoform,
        "bin/Vectoform",
    )

    JLLWrappers.@init_executable_product(
        Vector_systems,
        "bin/Vector_systems",
    )

    JLLWrappers.@init_executable_product(
        Vor_vertices,
        "bin/Vor_vertices",
    )

    JLLWrappers.@init_executable_product(
        ZZprog,
        "bin/ZZprog",
    )

    JLLWrappers.@init_executable_product(
        Z_equiv,
        "bin/Z_equiv",
    )

    JLLWrappers.@init_executable_product(
        Zass_main,
        "bin/Zass_main",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
